server:
  port: 8080
  shutdown: graceful

management:
  server.port: 8099
  endpoints.web.exposure.include: health,info,metrics,prometheus,mappings,beans,loggers,env,configprops
  endpoint.health.show-details: always

spring:
  jackson.mapper.sort-properties-alphabetically: true
  data.mongodb:
    uri: ${MONGO_DB_URI}
    database: petStoreDatabase

logging.level:
  root: INFO
  com.cgi.example.petstore.logging: INFO
  org.springframework.web.filter: DEBUG

external.apis.vaccinations:
  baseUrl: ${VACCINATIONS_URL}
  path: vaccinations/{vaccinationId}
